// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Fixed fixed1;
    
    private Gtk.Statusbar statusbar3;
    
    private Gtk.Label status;
    
    private Gtk.Button button1;
    
    private Gtk.Button button2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("vF7");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_notebook", Gtk.IconSize.LargeToolbar, 24);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.Resizable = false;
        this.AllowGrow = false;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.fixed1 = new Gtk.Fixed();
        this.fixed1.WidthRequest = 115;
        this.fixed1.Name = "fixed1";
        this.fixed1.HasWindow = false;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.statusbar3 = new Gtk.Statusbar();
        this.statusbar3.WidthRequest = 105;
        this.statusbar3.Sensitive = false;
        this.statusbar3.Name = "statusbar3";
        this.statusbar3.Spacing = 100;
        // Container child statusbar3.Gtk.Box+BoxChild
        this.status = new Gtk.Label();
        this.status.Name = "status";
        this.status.LabelProp = Mono.Unix.Catalog.GetString("off");
        this.statusbar3.Add(this.status);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.statusbar3[this.status]));
        w1.Position = 1;
        w1.Expand = false;
        w1.Fill = false;
        this.fixed1.Add(this.statusbar3);
        Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.statusbar3]));
        w2.X = 2;
        w2.Y = 75;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.button1 = new Gtk.Button();
        this.button1.WidthRequest = 105;
        this.button1.CanFocus = true;
        this.button1.Events = ((Gdk.EventMask)(256));
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Video on");
        this.fixed1.Add(this.button1);
        Gtk.Fixed.FixedChild w3 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
        w3.X = 5;
        w3.Y = 5;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.button2 = new Gtk.Button();
        this.button2.WidthRequest = 105;
        this.button2.CanFocus = true;
        this.button2.Events = ((Gdk.EventMask)(256));
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Video off");
        this.fixed1.Add(this.button2);
        Gtk.Fixed.FixedChild w4 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
        w4.X = 5;
        w4.Y = 40;
        this.Add(this.fixed1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 133;
        this.DefaultHeight = 121;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
    }
}
